### ISSUE TITLE
Ability to edit shows mid run

### ISSUE THREAD

**Issue by nhyty** [newtheatre/nt-tickets#129]
This is useful for changing capacity midrun or adding more shows mid run

**Comment by davidtaylorhq** [comment]
@nhyty Pretty sure I fixed this

**Comment by nhyty** [comment]
@davidtaylorhq you didnt

**Comment by davidtaylorhq** [comment]
@nhyty What error are you seeing?

**Comment by nhyty** [comment]
@davidtaylorhq aying something about shows need to be in the future

**Comment by nhyty** [comment]
should be closed here https://github.com/newtheatre/nt-tickets/commit/0af47624f0b65a9c2baa9ea01830791a880678bb
