### ISSUE TITLE
Jump ship from Mandrill

### ISSUE THREAD

**Issue by wjdp** [newtheatre/nt-tickets#35]
It'll cost money from 27/04/16, and possibly break before then. See http://blog.mandrill.com/important-changes-to-mandrill.html.

Jump ship to the AWS solution?

**Comment by harry-bridge** [comment]
Jumping ship is already in the works, moving to SES which will be free for the amount of emails we send monthly, will get it set up when it's deployed on EC2 :boat:

**Comment by wjdp** [comment]
smashing!

**Comment by harry-bridge** [comment]
<img src="http://orig15.deviantart.net/a041/f/2015/240/b/b/smashing_patrick_by_matthewbooks-d97h35z.png">

**Comment by tomtom5152** [comment]
That's not a huge amount of notice.

Be advised for SES you have to have a complaints and bounce procedure in
place before hand, although from experience. This can be manual, they might
just ask for a copy of it.

**Comment by harry-bridge** [comment]
Yeah the bounce and complaint thing can be as simple as a handler that just removes the bounced email from the mailing list.

**Comment by tomtom5152** [comment]
There's a library to be written in there somewhere.

**Comment by harry-bridge** [comment]
like [django-ses](https://github.com/django-ses/django-ses)?

**Comment by tomtom5152** [comment]
From memory that doesn't deal with SES rate limiting at all, which can be a real problem. It also runs on the main thread so your response will block whilst waiting for SES to respond. One that gets around this problem is [sea-cucumber](https://github.com/duointeractive/sea-cucumber) but that now appears to be unmaintained.

**Comment by harry-bridge** [comment]
May give that a try, I haven't looked at handling SES in django in great detail yet though.

**Comment by tomtom5152** [comment]
You can just use SMTP if you really want to (useful for testing), but the boto library is much more powerful and will handle a lot of things for you automatically.

**Comment by harry-bridge** [comment]
I would prefer to use boto as that is made for AWS, also would be less work :+1:

**Comment by wjdp** [comment]
> That's not a huge amount of notice

I'm rather upset with them, they ran a decent service

**Comment by tomtom5152** [comment]
Just seen this on discourse meta which may be of interest. https://meta.discourse.org/t/mandrill-is-going-to-paid-plans-on-mailchimp/40134/2?u=itsghost

**Comment by wjdp** [comment]
Ooh, looks nice

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

You can send 100,000 free emails per month.

**Comment by harry-bridge** [comment]
Now fully moved to SES for booking notifications, could implement a mailing list if we wanted
