### ISSUE TITLE
/list/ "Book Tickets" link is mangled

### ISSUE THREAD

**Issue by wjdp** [newtheatre/nt-tickets#37]
![image](https://cloud.githubusercontent.com/assets/1690934/13447208/842231c2-e011-11e5-8ba6-b3f0c7289b2e.png)

**Comment by harry-bridge** [comment]
whats wrong with this

**Comment by wjdp** [comment]
The `/list/` page book link sends you to `http://beta.ticketing.newtheatre.org.uk/list/newtheatre.org.uk/book/111/`

**Comment by wjdp** [comment]
Try browsing from `/sidebar/` and `/list/`

**Comment by harry-bridge** [comment]
ahh I see
