### ISSUE TITLE
/sidebar/ gives 500

### ISSUE THREAD

**Issue by wjdp** [newtheatre/nt-tickets#38]
![image](https://cloud.githubusercontent.com/assets/1690934/13447228/a338fd02-e011-11e5-9ab8-f88c53c85771.png)

**Comment by harry-bridge** [comment]
Django can't find the PUBLIC_CATEGORIES setting, any idea what these were
<img width="921" alt="screen shot 2016-03-02 at 01 05 33" src="https://cloud.githubusercontent.com/assets/5897290/13447360/e6ed58bc-e012-11e5-9dc3-392b7514ace1.png">

**Comment by wjdp** [comment]
I think was a list of categories that would show up publicly, something like

``` python
PUBLIC_CATEGORIES = ['theatre','fringe']
```

Or whatever

**Comment by harry-bridge** [comment]
Thanks

**Comment by wjdp** [comment]
![image](https://cloud.githubusercontent.com/assets/1690934/13447439/6ed3c4fa-e013-11e5-87d5-3a6fe009b6a0.png)

**Comment by harry-bridge** [comment]
Awesome

**Comment by harry-bridge** [comment]
oops failing with titles

**Comment by harry-bridge** [comment]
Turns out 4am me can't read code
