### ISSUE TITLE
Lack of styling on booking form, and JS

### ISSUE THREAD

**Issue by wjdp** [newtheatre/nt-tickets#39]
![image](https://cloud.githubusercontent.com/assets/1690934/13447237/bd54fca4-e011-11e5-8b13-2b9062b49fef.png)

vs

![image](https://cloud.githubusercontent.com/assets/1690934/13447238/c207fa44-e011-11e5-8bd8-960c37fe64ab.png)

**Comment by harry-bridge** [comment]
somewhere bootstrap hasn't been loaded hmm

**Comment by wjdp** [comment]
presume it's whatever package I used being old and shit

**Comment by harry-bridge** [comment]
Fixed in 2057b74
