### ISSUE TITLE
STUFF Ticketing

### ISSUE THREAD

**Issue by nhyty** [newtheatre/nt-tickets#44]
Make this work again please! Shows set to StuFF don't show up on the STUFF page, this needs fixing. They should also not show up on the whats on page.

**Comment by harry-bridge** [comment]
Which STUFF page are they not showing on?

**Comment by nhyty** [comment]
@pickleshb http://newtheatre.org.uk/stuff/

**Comment by harry-bridge** [comment]
that's @wjdp's realm, how does pricing for STUFF work?

**Comment by wjdp** [comment]
Each show had a set price for everyone, this was stored in the show model and displayed on the stuff page.

I _think_ the stuff page tries to load from `/list/stuff/`, check the patch I sent you. It's all in there.

**Comment by harry-bridge** [comment]
that makes life a lot simpler and I'll have a look at that

**Comment by davidtaylorhq** [comment]
Tis done
