### ISSUE TITLE
Show Warnings

### ISSUE THREAD

**Issue by harry-bridge** [newtheatre/nt-tickets#68]
Should be able to add warnings to shows like smoking, strobe, foul dirty language, etc to appear on the website and screens to warn people a little more in advance than after they have bought their tickets,

**Comment by wjdp** [comment]
Ensure you use "offensive language" rather than dirty/bad etc

**Comment by harry-bridge** [comment]
@wjdp Yeah will get the wording checked by suitable foh/person who can English properly first

**Comment by samozzy** [comment]
Made a start on this. Content warnings appear on the booking page, as well as the ticket purchase page (for FOH to read to people looking to buy tickets). Implemented as a ManyToMany model.
![content_warnings](https://user-images.githubusercontent.com/15388319/32254777-093442d8-be9b-11e7-8951-4715517b56be.png)

**Comment by harry-bridge** [comment]
@samozzy Looking good, would say icons are easier to read than words and add tooltips for accessability, I'll see if I can find the ones I made

**Comment by samozzy** [comment]
@pickleshb Agreed. Have added the ability to use icons, so just a case of sourcing them.

**Comment by samozzy** [comment]
Looked into icons today. The crux is that I don’t think we’ll be able to find a set that has everything we’d like and all look the same short of making our own. That said, I have also only found that the only people to use icons are [PEGI](https://www.virodisplay.co.uk/collections/gender-neutral-toilet-signs/products/unisex-symbol-toilet-sign?lshst=collection) and [CERO](https://www.virodisplay.co.uk/collections/gender-neutral-toilet-signs/products/unisex-symbol-toilet-sign?lshst=collection) have icons for games, while BBFC uses words for films, and British TV also only uses words, so while nice, we’d be going with the current trend by only having words for now.

**Comment by tomtom5152** [comment]
Would using something like a colour coded [badge](https://v4-alpha.getbootstrap.com/components/badge/) work nicely for this. Make it distinct on the screen but also easy to recognise and sorted by severity/category etc?

**Comment by samozzy** [comment]
Sounds good. Looking at the warnings from this season, I’d suggest categories of action (sexual scenes, violence, murder), dialogue (discussions of suicide, adult references, innuendo) and technical (smoke, haze, strobe).

**Comment by nhyty** [comment]
@samozzy Innuendo, seriously

**Comment by samozzy** [comment]
@nhyty I said at the time that if anything this would encourage me to see the show more than detract!

**Comment by nhyty** [comment]
@samozzy But pg films have it in abundance and don't mention it.

**Comment by nhyty** [comment]
@nhyty Like imagine shrek warning about it

**Comment by samozzy** [comment]
@nhyty I agree, I’m not saying it should be one, just that it has been one recently (and would fit into the dialogue category quite nicely).

**Comment by nhyty** [comment]
@samozzy also, panto.

**Comment by samozzy** [comment]
![warnings](https://user-images.githubusercontent.com/15388319/34699321-7978761c-f4d4-11e7-8112-98e7fb6c5557.png)
Using Materialize [chips ](http://materializecss.com/chips.html)for the badge effect and [Tooltips](http://materializecss.com/dialogs.html).
